import { useState } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';

import CommonLayout from '@/components/CommonLayout';
import Modal from '@/components/Modal';
import NewReviewForm from '@/components/Forms/NewReviewForm';
import Feedback from '@/components/Forms/Feedback';
import Breadcrumbs from '@/components/Breadcrumbs';

import SingleReview from '@/components/SingleReview';

import { reviews } from '@/common/reviews/reviews';

export default function ReviewPage({ reviews }) {
  const router = useRouter();

  const [modal, setModal] = useState(null);

  const [review] = useState(reviews.find((item) => item.id == router.query.id));

  return (
    <>
      <Head>
        <title>Отзывы о компаниях</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CommonLayout setModal={setModal}>
        <main>
          <Breadcrumbs review={review} nameOfHomePage="LEOMAX.RU — отзывы" />
          {review && <SingleReview review={review} setModal={setModal} />}
        </main>
      </CommonLayout>
      {modal && <Modal setModal={setModal}>{modal === 'newReview' ? <NewReviewForm /> : modal === 'feedback' ? <Feedback /> : <h1>Комментарий</h1>}</Modal>}
    </>
  );
}

export const getStaticProps = async () => {
  return {
    props: {
      reviews,
    },
  };
};

export const getStaticPaths = async () => {
  const paths = reviews.map((review) => ({
    params: { id: review.id.toString() },
  }));

  return {
    paths,
    fallback: false,
  };
};
